### ISSUE TITLE
Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW

### ISSUE THREAD

**Issue by AnotherEntity** [Wurst-Imperium/Wurst7#39]
I followed setup instructions for win10 eclipse, then tried to run it in eclipse
haven't made any changes to the source code but when trying to launch minecraft crashes returning...

```
 Launched Version: Fabric
 Backend library: LWJGL version 3.2.2 build 10
 Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
 GL Caps: 
 Using VBOs: Yes
 Is Modded: Definitely; Client brand changed to 'fabric'
 Type: Client (map_client.txt)
 CPU: <unknown>
 #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\mcc\Wurst7-master\run\.\crash-reports\crash-2019-12-22_16.55.22-client.txt
```

[latest.log](https://github.com/Wurst-Imperium/Wurst7/files/3993243/latest.log)

**Comment by AnotherEntity** [comment]
fixed the issue myself by downloading lwjgl 3.2.2 library and adding it as a referenced library in eclipse.

**Comment by Void-heart** [comment]
@AFelidae Could you please tell "how did you download lwjgl 3.2.2"?
I tried by myself to add 64-bit VM version of lwjgl 3.2.2...And tried to relocate Libraries location...
But hasn't helped...

**Comment by AFelidae** [comment]
Might be worth trying intellij if you haven't already. I haven't managed to reproduce the issue while using `gradlew runClient`.

I was able to add an external jar lwjgl.jar which I downloaded from their website https://www.lwjgl.org/browse/release/3.2.2/bin/lwjgl

**Comment by Void-heart** [comment]
@AFelidae Thank you for your reply. Yeah, I actually have used IntelliJ to do all of these things, including `runClient` and replacing `lwjgl.jar`. But didn't worked...Always still the same problem as yours happens...

**Comment by Void-heart** [comment]
OK. I used the "Systematic debugging method" to exclude probabilities one by one. I found the configuration in `Minecraft Client` or `Minecraft Server` wasn't properly set. Or should I say we should delete the `.idea` file first when we download Minecraft MOD source code from GitHub...Because there's `.cfg` file location written. And the `.cfg` file manages lwjgl API.

For instance, if the `Minecraft_Client.xml` file is written down `V:\Users\...\Desktop` is your `.cfg` location but your ACTUAL `.cfg` file is in OTHER place, like your Music file, then the crash happens.
This could be done by a slide-down menu button near the "Run" green button(OK, I think you've already known this.).

I guess it could be caused by "move whole project file by just dragging or copy/paste", "forgot to delete it or put it in `.gitignore` file before updating by Git" etc..
