### ISSUE TITLE
Crashes during AutoFish ing

### ISSUE THREAD

**Issue by NickUfer** [Wurst-Imperium/Wurst7#726]
## Description

Client either crashes or exists server with error `Accessing LegacyRandomSource from multiple threads`

## Steps To Reproduce
1. Go AFK fishing

## Crash Report
```
Reported exception thrown!
net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:88)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_638.method_2943(class_638.java:377)
	at net.minecraft.class_638.method_2941(class_638.java:358)
	at net.minecraft.class_310.method_1574(class_310.java:1892)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	... 12 more


---- Minecraft Crash Report ----
// Sorry :(

Time: 2022-10-31 18:13:14
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_638.method_2943(class_638.java:377)
	at net.minecraft.class_638.method_2941(class_638.java:358)
	at net.minecraft.class_310.method_1574(class_310.java:1892)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_638.method_2943(class_638.java:377)
	at net.minecraft.class_638.method_2941(class_638.java:358)

-- Thread dumps --
Details:
	Thread dumps: Render thread: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_638.method_2943(class_638.java:377)
	at net.minecraft.class_638.method_2941(class_638.java:358)
	at net.minecraft.class_310.method_1574(class_310.java:1892)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Stacktrace:
	at net.minecraft.class_5798.method_33564(class_5798.java:84)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:27)
	at net.minecraft.class_638.method_2943(class_638.java:377)
	at net.minecraft.class_638.method_2941(class_638.java:358)
	at net.minecraft.class_310.method_1574(class_310.java:1892)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['redacted'/839932, l='ClientLevel', x=7801.00, y=64.00, z=27464.99]]
	Chunk stats: 4096, 856
	Level dimension: minecraft:overworld
	Level spawn location: World: (7803,73,27264), Section: (at 11,9,0 in 487,4,1704; chunk contains blocks 7792,-64,27264 to 7807,319,27279), Region: (15,53; contains chunks 480,1696 to 511,1727, blocks 7680,-64,27136 to 8191,319,27647)
	Level time: 164620 game time, 1625681583 day time
	Server brand: Waterfall <- redacted server
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_r696344.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.0.6-060006-generic
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 779636968 bytes (743 MiB) / 3087007744 bytes (2944 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 5.08
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 16640.00
	Graphics card #0 deviceId: 0x73bf
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 20105.43
	Virtual memory used (MB): 10006.05
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 6.2.46
		autoclicker-fabric: Auto Clicker 1.19.2-1.4.2-build.9999
		baritone: Baritone 1.8.3-136-gec2941be-dirty
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.21+93d8cb8290
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.19+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.11+c6af733c90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.13+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.4.0.274
		lazydfu: LazyDFU 0.1.3
		lightoverlay: Light Overlay 7.0.0
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		seedcrackerx: SeedCrackerX 2.13.1
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core d685a37f0a466d4bf800e7f285daf9ef73c81678
			com_seedfinding_mc_feature: mc_feature c29fd1fcd746e14c1bcdb127da3113ba273db1fd
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		shulkerboxtooltip: Shulker Box Tooltip 3.1.3+1.19.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		wurst: Wurst Client v7.28-MC1.19.2
		xaerominimap: Xaero's Minimap 22.15.1
		xaeroworldmap: Xaero's World Map 1.28.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 6900 XT (navi21, LLVM 15.0.2, DRM 3.48, 6.0.6-060006-generic) GL version 4.6 (Core Profile) Mesa 22.2.1, AMD
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=2, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='0:240(14): warning: `lmCoord' used uninitialized' x 1
id=3, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='0:240(14): warning: `lmCoord' used uninitialized' x 1
id=4, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='0:253(14): warning: `lmCoord' used uninitialized' x 1
id=5, source=SHADER COMPILER, type=OTHER, severity=HIGH, message='0:253(14): warning: `lmCoord' used uninitialized' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks_r696344.zip
	Current Language: English (US)
	CPU: 32x AMD Ryzen 9 5950X 16-Core Processor
```

**Comment by omerien** [comment]
Same as #725

**Comment by Alexander01998** [comment]
> wurst: Wurst Client v7.28-MC1.19.2

It looks like you are using an outdated version of Wurst. Please try updating to [Wurst 7.30](https://www.wurstclient.net/updates/wurst-7-30/?mc=1.19.2) and let me know if that fixes the issue or changes the error message.

**Comment by Alexander01998** [comment]
Hey @NickUfer! Have you had the chance to try this again with the latest commit? I've been working on improving AutoFish over the past few days and it's a lot better now. I couldn't reproduce the exact issue you're describing, but I'm optimistic that these improvements should fix it. Please let me know how it goes.

**Comment by NickUfer** [comment]
Hey @Alexander01998, just tested it again with the latest stable version (v7.34), but still happens

![image](https://github.com/Wurst-Imperium/Wurst7/assets/11254522/33a708e0-3889-4e3e-b12c-bcfa03acc919)

```
[19:34:14] [Netty Epoll Client IO #2/ERROR]: Thread dumps: 
Netty Epoll Client IO #2: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43057(class_6566.java:56)
	at net.minecraft.class_1787.method_7836(class_1787.java:27)
	at net.minecraft.class_1799.method_7913(class_1799.java:286)
	at net.minecraft.class_636.method_41929(class_636.java:391)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2919(class_636.java:383)
	at net.minecraft.class_310.method_1583(class_310.java:1819)
	at net.minecraft.class_310.rightClick(class_310.java:8664)
	at net.wurstclient.hacks.AutoFishHack.rightClick(AutoFishHack.java:192)
	at net.wurstclient.hacks.AutoFishHack.onReceivedPacket(AutoFishHack.java:173)
	at net.wurstclient.events.PacketInputListener$PacketInputEvent.fire(PacketInputListener.java:40)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_2535.handler$bdp000$wurst$onChannelRead0(class_2535.java:1044)
	at net.minecraft.class_2535.method_10770(class_2535.java:155)
	at net.minecraft.class_2535.channelRead0(class_2535.java:52)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_5798.method_33564(class_5798.java:88)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_5820.method_43156(class_5820.java:49)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_6566.method_43057(class_6566.java:56)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_1787.method_7836(class_1787.java:27)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7913(class_1799.java:286)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_636.method_41929(class_636.java:391)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_636.method_41931(class_636.java:278)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_636.method_2919(class_636.java:383)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1583(class_310.java:1819)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_310.rightClick(class_310.java:8664)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoFishHack.rightClick(AutoFishHack.java:192)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoFishHack.onReceivedPacket(AutoFishHack.java:173)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.events.PacketInputListener$PacketInputEvent.fire(PacketInputListener.java:40)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$bdp000$wurst$onChannelRead0(class_2535.java:1044)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10770(class_2535.java:155)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelRead0(class_2535.java:52)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_5798.method_33564(class_5798.java:84)
[19:34:14] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	... 60 more
```

**Comment by Alexander01998** [comment]
Thanks @NickUfer, but please test with [Wurst 7.35](https://www.wurstclient.net/updates/wurst-7-35/). That's the one with the AutoFish improvements, not 7.34. Sorry for the confusion!

**Comment by NickUfer** [comment]
@Alexander01998 I'm now using version 7.35. Already going for ~1.5h without any issues, looking good.
